name: TekelalaSAS
favicon: null
layout_spectrum: 0.9603107161819935
typography_spectrum: 0.6108128223568201
title: Tekelala your ally for your digital transformation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff0000'
    - '#b5a59b'
    - '#5d4d42'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
